version: '3.7'
services:
  server:
    build: 
      context: ./server
    ports:
      - 8000
    volumes:
      - ./:/usr/src/app/
      - ./.vscode:/usr/src/app/server/.vscode
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    init: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
    networks:
      - default
      - netbox
  db:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - default
  client:
    build: ./client
    ports:
      - 3000
    volumes:
      - ./:/app
      - ./.vscode:/app/client/.vscode
      - /app/client/node_modules
    env_file:
      - .env
    init: true
    networks:
      - default

volumes:
  postgres:
networks:
  default:
  netbox:
    name: netbox-docker_default
    external: true
